version: '2'
volumes:
  volume_data:
  node-red-data:
services:
  python-evdev2mqtt:
    build: ./python-evdev2mqtt
    privileged: true
  node-red:
    build: ./node-red
    privileged: true
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
    labels:
      io.balena.features.kernel-modules: '1'
    environment:
      - TZ=Europe/Brussels
  mqtt:
    image: arm32v6/eclipse-mosquitto #https://hub.docker.com/_/eclipse-mosquitto   
    #image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
      