version: '2'
volumes:
  volume_data:
  node-red-data:
services:
  keypad2mqtt:
    build: ./keypad2mqtt
    privileged: true
  samba-rsync:
    build: ./samba-rsync
    privileged: true
    volumes:
      - 'volume_data:/data'
    ports:
      - "139:139"
      - "445:445"
    environment:
      - UDEV=1  # see https://www.balena.io/docs/reference/base-images/base-images/#working-with-dynamically-plugged-devices
  node-red:
    build: ./node-red
    privileged: true
    volumes:
       - 'node-red-data:/data'
    ports:
       - "1880:1880"
    depends_on:
        - mqtt
    restart: always
    labels:
      io.balena.features.kernel-modules: '1'
    environment:
      - TZ=Europe/Brussels
  mqtt:
    #image: arm32v6/eclipse-mosquitto #https://hub.docker.com/_/eclipse-mosquitto   
    image: panuwitp/mosquitto-arm
    ports:
      - "1883:1883"
      